#!/usr/bin/env sh

if [ "$PODSPEC" ]; then
  TASK="podspec:lint"
else
  TASK="test"

  if [ "$XCTOOL" ]; then TASK="$TASK:xctool"; fi
  TASK="$TASK:$PLATFORM"
fi

echo "Executing rake task: $TASK"
rake "$TASK"
