#!/usr/bin/env bash
set -e

curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
swiftenv install 2.2.1 && swiftenv local 2.2.1
export SWIFT_EXEC="$(swiftenv which swiftc)"
export SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-05-09-a
swiftenv install $SWIFT_VERSION && swiftenv local $SWIFT_VERSION