#!/usr/bin/env sh

rake test:ios
rake test:osx
rake test:xctool:ios

# Due to the `pending` specs using a `print` xctool fails generating the report,
# which in turn makes the tests fail.
# See https://github.com/facebook/xctool/issues/314#issuecomment-152988101 and comments
# for details.
# See https://circleci.com/gh/mokagio/Quick/12 for a proof that without `print` the test pass.
#rake test:xctool:osx
