name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.1.0
